# Generated by Django 3.1.6 on 2021-03-06 21:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_category', models.CharField(max_length=50)),
                ('task_short_description', models.CharField(max_length=140)),
                ('task_added_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='BoardTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_start_date', models.DateField(verbose_name='start date task')),
                ('task_end_date', models.DateField(verbose_name='end date task')),
                ('task_start_time', models.TimeField(verbose_name='start time task')),
                ('task_end_time', models.TimeField(verbose_name='end time task')),
                ('task_comment', models.CharField(max_length=140)),
                ('task_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('task_done', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task')),
            ],
        ),
    ]
