# Generated by Django 3.1.6 on 2021-02-18 15:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('category_name', models.CharField(max_length=30)),
                ('quick_description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='MySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=140)),
                ('task_date', models.DateTimeField(verbose_name='date when the task is done')),
                ('task_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mytask')),
            ],
        ),
    ]
