# Generated by Django 3.1.6 on 2021-02-27 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_myschedule_mytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_start_date', models.DateTimeField(verbose_name='start task')),
                ('task_end_date', models.DateTimeField(verbose_name='end task')),
                ('task_comment', models.CharField(max_length=140)),
                ('task_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_category', models.CharField(max_length=50)),
                ('task_short_description', models.CharField(max_length=140)),
                ('task_added_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.DeleteModel(
            name='MySchedule',
        ),
        migrations.DeleteModel(
            name='MyTask',
        ),
        migrations.AddField(
            model_name='boardtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task'),
        ),
    ]
